#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
sed -i "$ a frontend load_balancer\n    bind *:80\n    mode http\n    default_backend web_servers\nbackend web_servers\n    balance roundrobin\n    server web-01 44.192.24.21:80 check\n    server web-02 3.235.29.102:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start
