#!/usr/bin/env bash
#checking file exists and stuff

name=school
if [ -e $name ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $name ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $name ]; then
    echo "school is a regular file"
fi
